### PR TITLE
Added Authentication Support for Private Repositories (Bitbucket, Github)

### LINKED ISSUE #48: namespace and stage variables are mandatory
I am using Terraform 0.12. If I don't specify the `namespace` and `stage` variables, I get the following error:

```
Error: Error creating CodeBuild project: InvalidParameter: 2 validation error(s) found.
- minimum field size of 1, CreateProjectInput.Tags[1].Value.
- minimum field size of 1, CreateProjectInput.Tags[2].Value.


  on .terraform/modules/codebuild/main.tf line 170, in resource "aws_codebuild_project" "default":
 170: resource "aws_codebuild_project" "default" {
```

My code is quite minimal, eg:

```
module "codebuild" {
  source  = "cloudposse/codebuild/aws"
  version = "0.17.0"

  name            = "${local.repo}-build"
  cache_enabled   = false
  artifact_type   = "NO_ARTIFACTS"
  source_type     = "CODECOMMIT"
  source_location = "https://git-codecommit.${data.aws_region.current.name}.amazonaws.com/v1/repos/${local.repo}"
  #namespace       = "test"
  #stage           = "test"
}
```

### LINKED ISSUE #54: Problem destroying IAM Role while destroying resources.
## Describe the Bug
Following error occurs while destroy.
```
Error deleting IAM Role (<role-id>): DeleteConflict: Cannot delete entity, must detach all policies first.
```

## Expected Behavior
A clean destroy 

## Steps to Reproduce
It does not occur after first apply, but happens after several applies.

## Screenshots
If applicable, add screenshots or logs to help explain your problem.

## Environment (please complete the following information):
Mac-Os

## Additional Context
Terragrunt

## Notes
All other resources are destroyed completely. Only iam role is kept. 

## Suggestion
```tf
resource "aws_iam_role" "default" {
  count              = var.enabled ? 1 : 0
  name               = module.label.id
  assume_role_policy = data.aws_iam_policy_document.role.json
  force_detach_policies = true
}
```

Current code does not contain `force_detach_policies = true``

## Pull Request
I've made correction adding some additional features .
#53

### PR DESCRIPTION
**Pull request by brcnblc**
## what
Added support for :
* private repository auth
* git_submodules_config
* vpc_config
* logs_config
* git_clone_depth
* source_version

* Closes #54 
Added `force_detach_policies = true` into resource "aws_iam_role" "default" 

* Closes #48 
Added to main.tf
```
tags            = {
    for name, value in module.label.tags:
      name => value
    if length(value) > 0
  }
```

## why
* Someone should do it 😄

### CODE REVIEW

**Comment by osterman** [comment]
@brcnblc please fix conflicts

**Comment by brcnblc** [comment]
I couldn't resolve conflict in README.yaml. Why does it give a conflict?

Also when I run test I get following error:
Running tests in  ../
1..10
ok 1 check if terraform is installed
not ok 2 check if terraform code needs formatting
# (from function `skip_if_disabled' in file test/.test-harness/test/terraform/lib.bash, line 12,
#  in test file test/.test-harness/test/terraform/lint.bats, line 4)
#   `skip_if_disabled' failed
# /Users/bircan/develop/github/terraform-aws-codebuild/test/.test-harness/test/terraform/lib.bash: line 12: ${env^^}: bad substitution
ok 3 check if terraform modules are valid
not ok 4 check if terraform modules are properly pinned
# (from function `setup' in test file test/.test-harness/test/terraform/module-pinning.bats, line 4)
#   `TMPFILE="$(mktemp /tmp/terraform-modules-XXXXXXXXXXX.txt)"' failed
# mktemp: mkstemp failed on /tmp/terraform-modules-XXXXXXXXXXX.txt: File exists
ok 5 check if terraform plugins are valid
ok 6 check if terraform providers are properly pinned
ok 7 check if terraform code is valid
ok 8 check if terraform-docs is installed
ok 9 check if terraform inputs have descriptions
ok 10 check if terraform outputs have descriptions
make: *** [module] Error 1

**Comment by brcnblc** [comment]
@osterman If you can supply private bitbucket repository credentials having access only to a sample repository used for this bitbucket example, then we can add a test step to check the bitbucket example.

**Comment by brcnblc** [comment]
> @osterman Resolved
> 
> Also when I run test I get following error:
> 
> ```
> Running tests in  ../

> not ok 2 check if terraform code needs formatting
> # (from function `skip_if_disabled' in file test/.test-harness/test/terraform/lib.bash, line 12,
> #  in test file test/.test-harness/test/terraform/lint.bats, line 4)
> #   `skip_if_disabled' failed
> # /Users/bircan/develop/github/terraform-aws-codebuild/test/.test-harness/test/terraform/lib.bash: line 12: ${env^^}: bad substitution

> not ok 4 check if terraform modules are properly pinned
> # (from function `setup' in test file test/.test-harness/test/terraform/module-pinning.bats, line 4)
> #   `TMPFILE="$(mktemp /tmp/terraform-modules-XXXXXXXXXXX.txt)"' failed
> # mktemp: mkstemp failed on /tmp/terraform-modules-XXXXXXXXXXX.txt: File exists

> make: *** [module] Error 1
> ```
FYI:
I sill get after running `test all` in locally cloned repo/test folder

**Comment by osterman** [comment]
@brcnblc what are your thoughts on if move this to a new module called `terraform-aws-codebuild-bitbucket`? That way we can keep the code paths separate and not complicate the modules trying to support both? Especially since we (cloudposse) have no way of testing bitbucket.

**Pull request merged**
