### PR TITLE
allow docker images pull in the build

### PR DESCRIPTION
**Pull request by gregory**
## what
* Describe high-level what changed as a result of these commits (i.e. in plain-english, what do these changes mean?)
> Allows to docker pull previous ecr images in the build. 

## why
* Provide the justifications for the changes (e.g. business case). 
> Without those extra Actions docker pull ECR images will fail. 
* Describe why these changes were made (e.g. why do these commits fix the problem?)
> I simply added the required permissions for it to work properly.

### CODE REVIEW

**Comment by gregory** [comment]
@SweetOps I'm not sure what kind of witchcraft this is, but I haven't touched the readme :) 

/thanks

**Comment by SweetOps** [comment]
hey @Gregory , sorry for so long delay... please rebase your branch with current `master`

**Review by jamengual — APPROVED** [review]

**Comment by jamengual** [comment]
@gregory can you rebase from master?

**Comment by joe-niland** [comment]
@gregory could you please allow upstream maintainers to make changes to your branch?
https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork#:~:text=to%20your%20branch.-,Enabling%20repository%20maintainer%20permissions%20on%20existing%20pull%20requests,like%20to%20allow%20commits%20on.

**Comment by SweetOps** [comment]
> @gregory could you please allow upstream maintainers to make changes to your branch?
https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork#:~:text=to%20your%20branch.-,Enabling%20repository%20maintainer%20permissions%20on%20existing%20pull%20requests,like%20to%20allow%20commits%20on. 

@gregory can you do this?

**Comment by jamengual** [comment]
no updates, closing.

**Pull request closed without merging**
